import { UNIT, BLDG } from './constants.js';

export const UNIT_DEF = {
  [UNIT.GROUNDSKEEPER]: {
    label: 'BB',
    name: 'Ball Boy',
    hp: 40,
    speed: 70,
    damage: 4,
    range: 32,
    attackSpeed: 1.0,
    isWorker: true,
    harvestRate: 10,
    carryMax: 15,
    cost: 50,
    trainTime: 12,
    radius: 10,
    isRanged: false,
    projectileSpeed: 0,
    playerColor: '#90caf9',
    enemyColor: '#ef9a9a'
  },
  [UNIT.BATTER]: {
    label: 'B',
    name: 'Batter',
    hp: 90,
    speed: 68,
    damage: 22,
    range: 38,
    attackSpeed: 0.9,
    isWorker: false,
    harvestRate: 0,
    carryMax: 0,
    cost: 75,
    trainTime: 15,
    radius: 11,
    isRanged: false,
    projectileSpeed: 0,
    playerColor: '#4fc3f7',
    enemyColor: '#ef5350'
  },
  [UNIT.PITCHER]: {
    label: 'P',
    name: 'Pitcher',
    hp: 55,
    speed: 60,
    damage: 14,
    range: 170,
    attackSpeed: 0.75,
    isWorker: false,
    harvestRate: 0,
    carryMax: 0,
    cost: 100,
    trainTime: 18,
    radius: 10,
    isRanged: true,
    projectileSpeed: 280,
    playerColor: '#4fc3f7',
    enemyColor: '#ef5350'
  },
  [UNIT.CATCHER]: {
    label: 'C',
    name: 'Catcher',
    hp: 180,
    speed: 48,
    damage: 12,
    range: 36,
    attackSpeed: 0.65,
    isWorker: false,
    harvestRate: 0,
    carryMax: 0,
    cost: 125,
    trainTime: 22,
    radius: 13,
    isRanged: false,
    projectileSpeed: 0,
    playerColor: '#4fc3f7',
    enemyColor: '#ef5350'
  },
  [UNIT.SLUGGER]: {
    label: 'S',
    name: 'Slugger',
    hp: 130,
    speed: 55,
    damage: 40,
    range: 40,
    attackSpeed: 0.45,
    isWorker: false,
    harvestRate: 0,
    carryMax: 0,
    cost: 150,
    trainTime: 25,
    radius: 12,
    isRanged: false,
    projectileSpeed: 0,
    playerColor: '#4fc3f7',
    enemyColor: '#ef5350'
  }
};

export const BLDG_DEF = {
  [BLDG.DUGOUT]: {
    name: 'Dugout',
    label: 'DUG',
    hp: 1000,
    isMain: true,
    cost: 0,
    buildTime: 0,
    tileW: 3,
    tileH: 3,
    trainable: [UNIT.GROUNDSKEEPER],
    isAttacker: false,
    attackDamage: 0,
    attackRange: 0,
    attackSpeed: 0,
    isRanged: false
  },
  [BLDG.BATTING_CAGE]: {
    name: 'Batting Cage',
    label: 'BC',
    hp: 450,
    isMain: false,
    cost: 150,
    buildTime: 20,
    tileW: 2,
    tileH: 2,
    trainable: [UNIT.BATTER, UNIT.CATCHER],
    isAttacker: false,
    attackDamage: 0,
    attackRange: 0,
    attackSpeed: 0,
    isRanged: false
  },
  [BLDG.BULLPEN]: {
    name: 'Bullpen',
    label: 'BP',
    hp: 450,
    isMain: false,
    cost: 175,
    buildTime: 20,
    tileW: 2,
    tileH: 2,
    trainable: [UNIT.PITCHER, UNIT.SLUGGER],
    isAttacker: false,
    attackDamage: 0,
    attackRange: 0,
    attackSpeed: 0,
    isRanged: false
  },
  [BLDG.BLEACHERS]: {
    name: 'Bleachers',
    label: 'BL',
    hp: 350,
    isMain: false,
    cost: 125,
    buildTime: 15,
    tileW: 2,
    tileH: 2,
    trainable: [],
    isAttacker: true,
    attackDamage: 15,
    attackRange: 220,
    attackSpeed: 0.6,
    isRanged: true
  }
};
